config/routes.rb
Directory::Application.routes.draw do
  namespace :admin do
    resources :websites
  end

  resources :websites, only: [:show, :index]

end

app/models/website.rb
class Website < ActiveRecord::Base
end

app/controllers/admin/websites_controller.rb
class Admin::WebsitesController < ApplicationController
  before_action :set_website, only: [:show, :edit, :update, :destroy]

  # GET /websites
  # GET /websites.json
  def index
    @websites = Website.all
  end

  # GET /websites/1
  # GET /websites/1.json
  def show
  end

  # GET /websites/new
  def new
    @website = Website.new
  end

  # GET /websites/1/edit
  def edit
  end

  # POST /websites
  # POST /websites.json
  def create
    @website = Website.new(website_params)

    respond_to do |format|
      if @website.save
        format.html { redirect_to admin_website_url(@website), notice: 'Website was successfully created.' }
        format.json { render action: 'show', status: :created, location: admin_website_url(@website) }
      else
        format.html { render action: 'new' }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /websites/1
  # PATCH/PUT /websites/1.json
  def update
    respond_to do |format|
      if @website.update(website_params)
        format.html { redirect_to admin_website_url(@website), notice: 'Website was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /websites/1
  # DELETE /websites/1.json
  def destroy
    @website.destroy
    respond_to do |format|
      format.html { redirect_to admin_websites_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_website
      @website = Website.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def website_params
      params.require(:website).permit(:name, :url, :description)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController

  layout "consumer"

  before_action :set_locate

  # GET /websites
  # GET /websites.json
  def index
    @websites = Website.all
  end

  # GET /websites/1
  # GET /websites/1.json
  def show
    @website = Website.find(params[:id])
  end

  private

  def set_locate
    I18n.locale = params[:locale]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/admin/websites/_form.html.erb
<%= form_for([:admin, @website]) do |f| %>
  <% if @website.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@website.errors.count, "error") %> prohibited this website from being saved:</h2>

      <ul>
      <% @website.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/websites/edit.html.erb
<h1>Editing website</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_website_path(@website) %> |
<%= link_to 'Back', admin_websites_path %>

app/views/admin/websites/index.html.erb
<h2>Listing websites</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @websites.each do |website| %>
      <tr>
        <td><%= website.name %></td>
        <td><%= website.url %></td>
        <td><%= website.description %></td>
        <td><%= link_to 'Show', admin_website_path(website) %></td>
        <td><%= link_to 'Edit', edit_admin_website_path(website) %></td>
        <td><%= link_to 'Destroy', admin_website_path(website), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Website', new_admin_website_path %>

app/views/admin/websites/new.html.erb
<h1>New website</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_websites_path %>

app/views/admin/websites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @website.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @website.url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @website.description %>
</p>

<%= link_to 'Edit', edit_admin_website_path(@website) %> |
<%= link_to 'Back', admin_websites_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Directory</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/consumer.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Directory</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "consumer", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/websites/index.html.erb
<h1>Website Listing</h1>
<h2><%= t("subtitle") %></h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @websites.each do |website| %>
      <tr>
        <td><%= website.name %></td>
        <td><%= link_to 'Show', website %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/websites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @website.name %>
</p>

<p>
  <%= link_to "Click here to visit this website", @website.url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @website.description.html_safe %>
</p>

<%= link_to 'Back', websites_path %>